name: Build chiaki-ng macOSX x86_64

on:
  workflow_dispatch:

jobs:
  build-mac_x64:
    name: Build macOSX x86_64 version
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: melusina-org/setup-macports@v1
      - run: port version

      - name: Install macports dependencies
        run: |
          sudo port install --target-os=10.15 qt6 ffmpeg7 pkgconfig libopus openssl3 cmake ninja nasm libsdl2 protobuf-c py-protobuf speexDSP libplacebo wget json-c miniupnpc

      - name: Configure chiaki-ng
        run: |
          cmake -S . -B build -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DCHIAKI_ENABLE_CLI=OFF -DCHIAKI_ENABLE_STEAMDECK_NATIVE=OFF"

      - name: Build chiaki-ng
        run: |
          cmake --build build --config Release --clean-first --target chiaki

      - name: Deploy chiaki-ng
        run: |
          cp -a build/gui/chiaki.app chiaki-ng.app
          cp scripts/qtwebengine_import.qml gui/src/qml/
          macdeployqt chiaki-ng.app -qmldir="$PWD/gui/src/qml" -libpath=/opt/local/lib
          mkdir -p chiaki-ng.app/Contents/Resources/vulkan/icd.d
          wget https://github.com/KhronosGroup/MoltenVK/releases/download/v1.2.9/MoltenVK-macos.tar && tar xf MoltenVK-macos.tar
          cp MoltenVK/MoltenVK/dylib/macOS/* chiaki-ng.app/Contents/Resources/vulkan/icd.d
          macdeployqt chiaki-ng.app -qmldir="$PWD/gui/src/qml" -libpath=/opt/local/lib
          ln -s ../../../../../../../Frameworks chiaki-ng.app/Contents/Frameworks/QtWebEngineCore.framework/Helpers/QtWebEngineProcess.app/Contents
          ln -s libvulkan.1.dylib chiaki-ng.app/Contents/Frameworks/vulkan
          codesign --force --entitlements gui/entitlements.xml --deep --sign - chiaki-ng.app
          hdiutil create -srcfolder chiaki-ng.app chiaki-ng.dmg
          codesign --force --entitlements gui/entitlements.xml --deep --sign - chiaki-ng.dmg

      - name: Upload chiaki-ng Artifact
        uses: actions/upload-artifact@v4
        with:
          name: chiaki-ng-macos_x86_64-Release
          path: chiaki-ng.dmg
          if-no-files-found: error
          retention-days: 7